### PR TITLE
Feature ptsize

### PR DESCRIPTION
**Pull request by jcvdav**
This PR is based on #26. It provides support for a `pt.size` argument that controls the size of markets when `geom_style = "pointrange"` is used. In the absence of an argument, `pt.size` defaults to the values set in `GeomPoint$default_aes$size`. Checks are handled by `ggplot2` internals.

The `dev` branch seems to be inactive, so suggesting this be merged to `main` instead.

``` r
library(fixest)
library(ggiplot)
#> Loading required package: ggplot2

# These examples borrow from the fixest::iplot() documentation and the
# introductory package vignette.

#
## Example 1: Vanilla TWFE
#

data(base_did)
base_inter = base_did

est_did = feols(y ~ x1 + i(period, treat, 5) | id+period, base_inter)
# Default behaviour
ggiplot(est_did)
```

``` r

# Controling for pt.size
ggiplot(est_did, pt.size = 10)
```

<sup>Created on 2023-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by grantmcdermott** [comment]
Hmmm. Looks like quite a few tests are failing.

I'm out right now, but can you test locally with `tinytest::test_all()`?

The snapshots are only run on Ubuntu, so you'll need that distro. See here: https://github.com/vincentarelbundock/tinysnapshot

**Comment by jcvdav** [comment]
Fascinating... It passed all tests and checks locally. I'll do more digging to figure out what's going on on Monday.

**Comment by jcvdav** [comment]
Looks like the tests on `iplot_data` are the ones that are not passing, and it's all related to how CIs are calcuated in different versions of `fixest`:

Using the CRAN release (V0.11.0) I get the following:

```
> tinytest::test_all()
test_fixest_multi.R...........    0 tests    33ms [Exited at #5: Linux snapshots]
test_ggiplot.R................    0 tests    28ms [Exited at #5: Linux snapshots]
test_iplot_data.R.............   22 tests 4 fails 38ms
----- FAILED[data]: test_iplot_data.R<69--73>
 call| expect_equivalent(iplot_data_est[[col]], iplot_data_est_known[[col]], 
 call| -->    tolerance = tol)
 diff| Mean relative difference: 0.009186607
 ----- FAILED[data]: test_iplot_data.R<69--73>
 call| expect_equivalent(iplot_data_est_log[[col]], iplot_data_est_log_known[[col]], 
 call| -->    tolerance = tol)
 diff| Mean relative difference: 0.01716456
 ----- FAILED[data]: test_iplot_data.R<69--73>
 call| expect_equivalent(iplot_data_est[[col]], iplot_data_est_known[[col]], 
 call| -->    tolerance = tol)
 diff| Mean relative difference: 0.006470814
 FAILED[data]: test_iplot_data.R<69--73> expect_equivalent(iplot_data_est_log[[col]], iplot_data_est_log_known[[col]], ...
 
Showing 4 out of 22 results: 4 fails, 18 passes (0.1s)
```

Further inspecting [the test script](https://github.com/grantmcdermott/ggiplot/blob/main/inst/tinytest/test_iplot_data.R#L71) confirms that tests fail for `col = "ci_low"` or `"ci_high"`. This seems to be related to [this PR](https://github.com/lrberge/fixest/pull/408), since the ci values that are hard-coded into the test [here]((https://github.com/grantmcdermott/ggiplot/blob/main/inst/tinytest/test_iplot_data.R#L31)) seem to be retrieved using a t-distribution.

After installing the stable development version of `fixest`, the tinytests produce the following:

```
> tinytest::test_all()
test_fixest_multi.R...........    0 tests    0.1s [Exited at #5: Linux snapshots]
test_ggiplot.R................    0 tests    26ms [Exited at #5: Linux snapshots]
Loading required package: ggplot2
test_iplot_data.R.............   22 tests OK 0.7s
All ok, 22 results (0.8s)
```

Thoughts?

**Comment by grantmcdermott** [comment]
Ah, sorry I should have anticipated this. The dev version of **fixest** includes a dof correction to the `iplot` conf. interval calculation. https://github.com/lrberge/fixest/pull/408

The **ggiplot** test snapshots are built against this corrected dev version.

What I don't get, though, is why the GH Actions CI test suite for this PR isn't pulling in the latest dev version. I've specified the necessary remote in the DESCRIPTION file. I'll try to take a peak later today.

**Comment by grantmcdermott** [comment]
Hey JC, sorry for the delay on this. I've been working on support for (gg)coefplot, which has required a fairly major code refactoring... 

In the meantime, the new release of fixest has now reached CRAN. I have this change reflected in my coefplot branch, but for you purposes it might just be simplest to include them directly in this PR. We need only changed the DESCRIPTION file to require fixest >= 0.11.2 and can then drop the Remotes entry. Hopefully all the tests run properly once this update is completed.

**Comment by jcvdav** [comment]
I see you made the changes to the `DESCRIPTION` file, thanks for doing that. Unfortunately, it looks like some tests are still failing even when fixest 0.11.2 is [installed](https://github.com/grantmcdermott/ggiplot/actions/runs/7037635703/job/19152827113?pr=27#step:5:994). Thoughts?

**Comment by grantmcdermott** [comment]
Finally managed to test this locally and I can see what's causing them to fail now...

Background: Instead of using `geom_pointrange` (etc.) directly in the plot construction, I manually create the same effect by first running desired interval style (e.g., `geom_line` for CIs without heads), followed by `geom_point`  to get the point estimate. This produces the same effect as (say) a regular pointrange, but in a way that makes it easier to re-use other parts of the code internally (e.g., if a user asks for error bars or ribbons instead). HOWEVER... it does require some manually adjustment to the points themselves, since `geom_pointrange` & co. have a larger point size than vanilla `geom_point`.

The upshot is that using `GeomPointGeomPoint$default_aes$size` to get the "natural" point size is going to be too small.

**Comment by jcvdav** [comment]
I think defaulting to `pt.size = 2.5` is appropriate. I had also modified the `DESCRIPTION` file locally, hence the required merge. It should all be working now (?).

**Comment by grantmcdermott** [comment]
Checks passed 🎉

**Pull request merged**
